require('config.plugins.everforest')
require('config.plugins.treesitter')
require('config.plugins.telescope')
require('config.plugins.git')
require('config.plugins.lualine')
require('config.plugins.mini')
require('config.plugins.illuminate')
require('config.plugins.vim-test')
